void emulate_loadpb (OrcOpcodeExecutor *ex, int n);
void emulate_loadpw (OrcOpcodeExecutor *ex, int n);
void emulate_loadpl (OrcOpcodeExecutor *ex, int n);
void emulate_absb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_absb (OrcOpcodeExecutor *ex);
void emulate_addb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_addb (OrcOpcodeExecutor *ex);
void emulate_addssb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_addssb (OrcOpcodeExecutor *ex);
void emulate_addusb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_addusb (OrcOpcodeExecutor *ex);
void emulate_andb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_andb (OrcOpcodeExecutor *ex);
void emulate_andnb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_andnb (OrcOpcodeExecutor *ex);
void emulate_avgsb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_avgsb (OrcOpcodeExecutor *ex);
void emulate_avgub (OrcOpcodeExecutor *ex, int n);
void emulate_n16_avgub (OrcOpcodeExecutor *ex);
void emulate_cmpeqb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_cmpeqb (OrcOpcodeExecutor *ex);
void emulate_cmpgtsb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_cmpgtsb (OrcOpcodeExecutor *ex);
void emulate_copyb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_copyb (OrcOpcodeExecutor *ex);
void emulate_maxsb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_maxsb (OrcOpcodeExecutor *ex);
void emulate_maxub (OrcOpcodeExecutor *ex, int n);
void emulate_n16_maxub (OrcOpcodeExecutor *ex);
void emulate_minsb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_minsb (OrcOpcodeExecutor *ex);
void emulate_minub (OrcOpcodeExecutor *ex, int n);
void emulate_n16_minub (OrcOpcodeExecutor *ex);
void emulate_mullb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_mullb (OrcOpcodeExecutor *ex);
void emulate_mulhsb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_mulhsb (OrcOpcodeExecutor *ex);
void emulate_mulhub (OrcOpcodeExecutor *ex, int n);
void emulate_n16_mulhub (OrcOpcodeExecutor *ex);
void emulate_orb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_orb (OrcOpcodeExecutor *ex);
void emulate_shlb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_shlb (OrcOpcodeExecutor *ex);
void emulate_shrsb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_shrsb (OrcOpcodeExecutor *ex);
void emulate_shrub (OrcOpcodeExecutor *ex, int n);
void emulate_n16_shrub (OrcOpcodeExecutor *ex);
void emulate_signb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_signb (OrcOpcodeExecutor *ex);
void emulate_subb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_subb (OrcOpcodeExecutor *ex);
void emulate_subssb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_subssb (OrcOpcodeExecutor *ex);
void emulate_subusb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_subusb (OrcOpcodeExecutor *ex);
void emulate_xorb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_xorb (OrcOpcodeExecutor *ex);
void emulate_absw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_absw (OrcOpcodeExecutor *ex);
void emulate_addw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_addw (OrcOpcodeExecutor *ex);
void emulate_addssw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_addssw (OrcOpcodeExecutor *ex);
void emulate_addusw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_addusw (OrcOpcodeExecutor *ex);
void emulate_andw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_andw (OrcOpcodeExecutor *ex);
void emulate_andnw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_andnw (OrcOpcodeExecutor *ex);
void emulate_avgsw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_avgsw (OrcOpcodeExecutor *ex);
void emulate_avguw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_avguw (OrcOpcodeExecutor *ex);
void emulate_cmpeqw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_cmpeqw (OrcOpcodeExecutor *ex);
void emulate_cmpgtsw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_cmpgtsw (OrcOpcodeExecutor *ex);
void emulate_copyw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_copyw (OrcOpcodeExecutor *ex);
void emulate_maxsw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_maxsw (OrcOpcodeExecutor *ex);
void emulate_maxuw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_maxuw (OrcOpcodeExecutor *ex);
void emulate_minsw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_minsw (OrcOpcodeExecutor *ex);
void emulate_minuw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_minuw (OrcOpcodeExecutor *ex);
void emulate_mullw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_mullw (OrcOpcodeExecutor *ex);
void emulate_mulhsw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_mulhsw (OrcOpcodeExecutor *ex);
void emulate_mulhuw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_mulhuw (OrcOpcodeExecutor *ex);
void emulate_orw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_orw (OrcOpcodeExecutor *ex);
void emulate_shlw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_shlw (OrcOpcodeExecutor *ex);
void emulate_shrsw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_shrsw (OrcOpcodeExecutor *ex);
void emulate_shruw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_shruw (OrcOpcodeExecutor *ex);
void emulate_signw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_signw (OrcOpcodeExecutor *ex);
void emulate_subw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_subw (OrcOpcodeExecutor *ex);
void emulate_subssw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_subssw (OrcOpcodeExecutor *ex);
void emulate_subusw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_subusw (OrcOpcodeExecutor *ex);
void emulate_xorw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_xorw (OrcOpcodeExecutor *ex);
void emulate_absl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_absl (OrcOpcodeExecutor *ex);
void emulate_addl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_addl (OrcOpcodeExecutor *ex);
void emulate_addssl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_addssl (OrcOpcodeExecutor *ex);
void emulate_addusl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_addusl (OrcOpcodeExecutor *ex);
void emulate_andl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_andl (OrcOpcodeExecutor *ex);
void emulate_andnl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_andnl (OrcOpcodeExecutor *ex);
void emulate_avgsl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_avgsl (OrcOpcodeExecutor *ex);
void emulate_avgul (OrcOpcodeExecutor *ex, int n);
void emulate_n16_avgul (OrcOpcodeExecutor *ex);
void emulate_cmpeql (OrcOpcodeExecutor *ex, int n);
void emulate_n16_cmpeql (OrcOpcodeExecutor *ex);
void emulate_cmpgtsl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_cmpgtsl (OrcOpcodeExecutor *ex);
void emulate_copyl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_copyl (OrcOpcodeExecutor *ex);
void emulate_maxsl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_maxsl (OrcOpcodeExecutor *ex);
void emulate_maxul (OrcOpcodeExecutor *ex, int n);
void emulate_n16_maxul (OrcOpcodeExecutor *ex);
void emulate_minsl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_minsl (OrcOpcodeExecutor *ex);
void emulate_minul (OrcOpcodeExecutor *ex, int n);
void emulate_n16_minul (OrcOpcodeExecutor *ex);
void emulate_mulll (OrcOpcodeExecutor *ex, int n);
void emulate_n16_mulll (OrcOpcodeExecutor *ex);
void emulate_mulhsl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_mulhsl (OrcOpcodeExecutor *ex);
void emulate_mulhul (OrcOpcodeExecutor *ex, int n);
void emulate_n16_mulhul (OrcOpcodeExecutor *ex);
void emulate_orl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_orl (OrcOpcodeExecutor *ex);
void emulate_shll (OrcOpcodeExecutor *ex, int n);
void emulate_n16_shll (OrcOpcodeExecutor *ex);
void emulate_shrsl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_shrsl (OrcOpcodeExecutor *ex);
void emulate_shrul (OrcOpcodeExecutor *ex, int n);
void emulate_n16_shrul (OrcOpcodeExecutor *ex);
void emulate_signl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_signl (OrcOpcodeExecutor *ex);
void emulate_subl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_subl (OrcOpcodeExecutor *ex);
void emulate_subssl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_subssl (OrcOpcodeExecutor *ex);
void emulate_subusl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_subusl (OrcOpcodeExecutor *ex);
void emulate_xorl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_xorl (OrcOpcodeExecutor *ex);
void emulate_convsbw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_convsbw (OrcOpcodeExecutor *ex);
void emulate_convubw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_convubw (OrcOpcodeExecutor *ex);
void emulate_convswl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_convswl (OrcOpcodeExecutor *ex);
void emulate_convuwl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_convuwl (OrcOpcodeExecutor *ex);
void emulate_convwb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_convwb (OrcOpcodeExecutor *ex);
void emulate_convssswb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_convssswb (OrcOpcodeExecutor *ex);
void emulate_convsuswb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_convsuswb (OrcOpcodeExecutor *ex);
void emulate_convusswb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_convusswb (OrcOpcodeExecutor *ex);
void emulate_convuuswb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_convuuswb (OrcOpcodeExecutor *ex);
void emulate_convlw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_convlw (OrcOpcodeExecutor *ex);
void emulate_convssslw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_convssslw (OrcOpcodeExecutor *ex);
void emulate_convsuslw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_convsuslw (OrcOpcodeExecutor *ex);
void emulate_convusslw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_convusslw (OrcOpcodeExecutor *ex);
void emulate_convuuslw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_convuuslw (OrcOpcodeExecutor *ex);
void emulate_mulsbw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_mulsbw (OrcOpcodeExecutor *ex);
void emulate_mulubw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_mulubw (OrcOpcodeExecutor *ex);
void emulate_mulswl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_mulswl (OrcOpcodeExecutor *ex);
void emulate_muluwl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_muluwl (OrcOpcodeExecutor *ex);
void emulate_accw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_accw (OrcOpcodeExecutor *ex);
void emulate_accl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_accl (OrcOpcodeExecutor *ex);
void emulate_accsadubl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_accsadubl (OrcOpcodeExecutor *ex);
void emulate_swapw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_swapw (OrcOpcodeExecutor *ex);
void emulate_swapl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_swapl (OrcOpcodeExecutor *ex);
void emulate_select0wb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_select0wb (OrcOpcodeExecutor *ex);
void emulate_select1wb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_select1wb (OrcOpcodeExecutor *ex);
void emulate_select0lw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_select0lw (OrcOpcodeExecutor *ex);
void emulate_select1lw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_select1lw (OrcOpcodeExecutor *ex);
void emulate_mergewl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_mergewl (OrcOpcodeExecutor *ex);
void emulate_mergebw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_mergebw (OrcOpcodeExecutor *ex);
void emulate_splitlw (OrcOpcodeExecutor *ex, int n);
void emulate_n16_splitlw (OrcOpcodeExecutor *ex);
void emulate_splitwb (OrcOpcodeExecutor *ex, int n);
void emulate_n16_splitwb (OrcOpcodeExecutor *ex);
void emulate_addf (OrcOpcodeExecutor *ex, int n);
void emulate_n16_addf (OrcOpcodeExecutor *ex);
void emulate_subf (OrcOpcodeExecutor *ex, int n);
void emulate_n16_subf (OrcOpcodeExecutor *ex);
void emulate_mulf (OrcOpcodeExecutor *ex, int n);
void emulate_n16_mulf (OrcOpcodeExecutor *ex);
void emulate_divf (OrcOpcodeExecutor *ex, int n);
void emulate_n16_divf (OrcOpcodeExecutor *ex);
void emulate_sqrtf (OrcOpcodeExecutor *ex, int n);
void emulate_n16_sqrtf (OrcOpcodeExecutor *ex);
void emulate_maxf (OrcOpcodeExecutor *ex, int n);
void emulate_n16_maxf (OrcOpcodeExecutor *ex);
void emulate_minf (OrcOpcodeExecutor *ex, int n);
void emulate_n16_minf (OrcOpcodeExecutor *ex);
void emulate_cmpeqf (OrcOpcodeExecutor *ex, int n);
void emulate_n16_cmpeqf (OrcOpcodeExecutor *ex);
void emulate_cmpltf (OrcOpcodeExecutor *ex, int n);
void emulate_n16_cmpltf (OrcOpcodeExecutor *ex);
void emulate_cmplef (OrcOpcodeExecutor *ex, int n);
void emulate_n16_cmplef (OrcOpcodeExecutor *ex);
void emulate_convfl (OrcOpcodeExecutor *ex, int n);
void emulate_n16_convfl (OrcOpcodeExecutor *ex);
void emulate_convlf (OrcOpcodeExecutor *ex, int n);
void emulate_n16_convlf (OrcOpcodeExecutor *ex);
void emulate_loadb (OrcOpcodeExecutor *ex, int n);
void emulate_loadw (OrcOpcodeExecutor *ex, int n);
void emulate_loadl (OrcOpcodeExecutor *ex, int n);
void emulate_storeb (OrcOpcodeExecutor *ex, int n);
void emulate_storew (OrcOpcodeExecutor *ex, int n);
void emulate_storel (OrcOpcodeExecutor *ex, int n);
