
/* autogenerated by generate-emulation */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif
#include <math.h>
#include <orc/orc.h>


/* begin Orc C target preamble */
#define ORC_CLAMP(x,a,b) ((x)<(a) ? (a) : ((x)>(b) ? (b) : (x)))
#define ORC_ABS(a) ((a)<0 ? -(a) : (a))
#define ORC_MIN(a,b) ((a)<(b) ? (a) : (b))
#define ORC_MAX(a,b) ((a)>(b) ? (a) : (b))
#define ORC_SB_MAX 127
#define ORC_SB_MIN (-1-ORC_SB_MAX)
#define ORC_UB_MAX 255
#define ORC_UB_MIN 0
#define ORC_SW_MAX 32767
#define ORC_SW_MIN (-1-ORC_SW_MAX)
#define ORC_UW_MAX 65535
#define ORC_UW_MIN 0
#define ORC_SL_MAX 2147483647
#define ORC_SL_MIN (-1-ORC_SL_MAX)
#define ORC_UL_MAX 4294967295U
#define ORC_UL_MIN 0
#define ORC_CLAMP_SB(x) ORC_CLAMP(x,ORC_SB_MIN,ORC_SB_MAX)
#define ORC_CLAMP_UB(x) ORC_CLAMP(x,ORC_UB_MIN,ORC_UB_MAX)
#define ORC_CLAMP_SW(x) ORC_CLAMP(x,ORC_SW_MIN,ORC_SW_MAX)
#define ORC_CLAMP_UW(x) ORC_CLAMP(x,ORC_UW_MIN,ORC_UW_MAX)
#define ORC_CLAMP_SL(x) ORC_CLAMP(x,ORC_SL_MIN,ORC_SL_MAX)
#define ORC_CLAMP_UL(x) ORC_CLAMP(x,ORC_UL_MIN,ORC_UL_MAX)
#define ORC_SWAP_W(x) ((((x)&0xff)<<8) | (((x)&0xff00)>>8))
#define ORC_SWAP_L(x) ((((x)&0xff)<<24) | (((x)&0xff00)<<8) | (((x)&0xff0000)>>8) | (((x)&0xff000000)>>24))
#define ORC_PTR_OFFSET(ptr,offset) ((void *)(((unsigned char *)(ptr)) + (offset)))
#define ORC_MIN_NORMAL (1.1754944909521339405e-38)
#define ORC_DENORMAL(x) (((x) > -ORC_MIN_NORMAL && (x) < ORC_MIN_NORMAL) ? ((x)<0 ? (-0.0f) : (0.0f)) : (x))
#define ORC_MINF(a,b) (isnan(a) ? a : isnan(b) ? b : ((a)<(b)) ? (a) : (b))
#define ORC_MAXF(a,b) (isnan(a) ? a : isnan(b) ? b : ((a)>(b)) ? (a) : (b))
/* end Orc C target preamble */


void
emulate_absb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: absb */
    var0 = ORC_ABS(var4);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_addb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: addb */
    var0 = var4 + var5;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_addssb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: addssb */
    var0 = ORC_CLAMP_SB(var4 + var5);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_addusb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: addusb */
    var0 = ORC_CLAMP_UB((orc_uint8)var4 + (orc_uint8)var5);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_andb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: andb */
    var0 = var4 & var5;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_andnb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: andnb */
    var0 = (~var4) & var5;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_avgsb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: avgsb */
    var0 = (var4 + var5 + 1)>>1;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_avgub (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: avgub */
    var0 = ((orc_uint8)var4 + (orc_uint8)var5 + 1)>>1;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_cmpeqb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: cmpeqb */
    var0 = (var4 == var5) ? (~0) : 0;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_cmpgtsb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: cmpgtsb */
    var0 = (var4 > var5) ? (~0) : 0;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_copyb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: copyb */
    var0 = var4;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_loadb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: loadb */
    var0 = var4;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_maxsb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: maxsb */
    var0 = ORC_MAX(var4, var5);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_maxub (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: maxub */
    var0 = ORC_MAX((orc_uint8)var4, (orc_uint8)var5);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_minsb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: minsb */
    var0 = ORC_MIN(var4, var5);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_minub (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: minub */
    var0 = ORC_MIN((orc_uint8)var4, (orc_uint8)var5);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_mullb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: mullb */
    var0 = (var4 * var5) & 0xff;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_mulhsb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: mulhsb */
    var0 = (var4 * var5) >> 8;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_mulhub (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: mulhub */
    var0 = ((orc_uint32)(orc_uint8)var4 * (orc_uint32)(orc_uint8)var5) >> 8;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_orb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: orb */
    var0 = var4 | var5;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_shlb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  const int var24 = ((orc_union32 *)(ex->src_ptrs[1]))->i;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: shlb */
    var0 = var4 << var24;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_shrsb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  const int var24 = ((orc_union32 *)(ex->src_ptrs[1]))->i;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: shrsb */
    var0 = var4 >> var24;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_shrub (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  const int var24 = ((orc_union32 *)(ex->src_ptrs[1]))->i;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: shrub */
    var0 = ((orc_uint8)var4) >> var24;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_signb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: signb */
    var0 = ORC_CLAMP(var4,-1,1);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_storeb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: storeb */
    var0 = var4;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_subb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: subb */
    var0 = var4 - var5;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_subssb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: subssb */
    var0 = ORC_CLAMP_SB(var4 - var5);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_subusb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: subusb */
    var0 = ORC_CLAMP_UB((orc_uint8)var4 - (orc_uint8)var5);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_xorb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: xorb */
    var0 = var4 ^ var5;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_absw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: absw */
    var0 = ORC_ABS(var4);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_addw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: addw */
    var0 = var4 + var5;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_addssw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: addssw */
    var0 = ORC_CLAMP_SW(var4 + var5);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_addusw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: addusw */
    var0 = ORC_CLAMP_UW((orc_uint16)var4 + (orc_uint16)var5);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_andw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: andw */
    var0 = var4 & var5;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_andnw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: andnw */
    var0 = (~var4) & var5;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_avgsw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: avgsw */
    var0 = (var4 + var5 + 1)>>1;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_avguw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: avguw */
    var0 = ((orc_uint16)var4 + (orc_uint16)var5 + 1)>>1;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_cmpeqw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: cmpeqw */
    var0 = (var4 == var5) ? (~0) : 0;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_cmpgtsw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: cmpgtsw */
    var0 = (var4 > var5) ? (~0) : 0;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_copyw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: copyw */
    var0 = var4;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_loadw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: loadw */
    var0 = var4;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_maxsw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: maxsw */
    var0 = ORC_MAX(var4, var5);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_maxuw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: maxuw */
    var0 = ORC_MAX((orc_uint16)var4, (orc_uint16)var5);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_minsw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: minsw */
    var0 = ORC_MIN(var4, var5);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_minuw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: minuw */
    var0 = ORC_MIN((orc_uint16)var4, (orc_uint16)var5);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_mullw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: mullw */
    var0 = (var4 * var5) & 0xffff;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_mulhsw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: mulhsw */
    var0 = (var4 * var5) >> 16;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_mulhuw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: mulhuw */
    var0 = ((orc_uint32)((orc_uint16)var4) * (orc_uint32)((orc_uint16)var5)) >> 16;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_orw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: orw */
    var0 = var4 | var5;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_shlw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  const int var24 = ((orc_union32 *)(ex->src_ptrs[1]))->i;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: shlw */
    var0 = var4 << var24;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_shrsw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  const int var24 = ((orc_union32 *)(ex->src_ptrs[1]))->i;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: shrsw */
    var0 = var4 >> var24;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_shruw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  const int var24 = ((orc_union32 *)(ex->src_ptrs[1]))->i;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: shruw */
    var0 = ((orc_uint16)var4) >> var24;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_signw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: signw */
    var0 = ORC_CLAMP(var4,-1,1);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_storew (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: storew */
    var0 = var4;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_subw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: subw */
    var0 = var4 - var5;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_subssw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: subssw */
    var0 = ORC_CLAMP_SW(var4 - var5);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_subusw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: subusw */
    var0 = ORC_CLAMP_UW((orc_uint16)var4 - (orc_uint16)var5);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_xorw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: xorw */
    var0 = var4 ^ var5;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_absl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: absl */
    var0.i = ORC_ABS(var4.i);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_addl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: addl */
    var0.i = var4.i + var5.i;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_addssl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: addssl */
    var0.i = ORC_CLAMP_SL((orc_int64)var4.i + (orc_int64)var5.i);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_addusl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: addusl */
    var0.i = ORC_CLAMP_UL((orc_int64)(orc_uint32)var4.i + (orc_int64)(orc_uint32)var5.i);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_andl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: andl */
    var0.i = var4.i & var5.i;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_andnl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: andnl */
    var0.i = (~var4.i) & var5.i;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_avgsl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: avgsl */
    var0.i = ((orc_int64)var4.i + (orc_int64)var5.i + 1)>>1;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_avgul (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: avgul */
    var0.i = ((orc_uint64)(orc_uint32)var4.i + (orc_uint64)(orc_uint32)var5.i + 1)>>1;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_cmpeql (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: cmpeql */
    var0.i = (var4.i == var5.i) ? (~0) : 0;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_cmpgtsl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: cmpgtsl */
    var0.i = (var4.i > var5.i) ? (~0) : 0;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_copyl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: copyl */
    var0.i = var4.i;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_loadl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: loadl */
    var0.i = var4.i;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_maxsl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: maxsl */
    var0.i = ORC_MAX(var4.i, var5.i);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_maxul (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: maxul */
    var0.i = ORC_MAX((orc_uint32)var4.i, (orc_uint32)var5.i);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_minsl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: minsl */
    var0.i = ORC_MIN(var4.i, var5.i);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_minul (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: minul */
    var0.i = ORC_MIN((orc_uint32)var4.i, (orc_uint32)var5.i);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_mulll (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: mulll */
    var0.i = (var4.i * var5.i) & 0xffffffff;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_mulhsl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: mulhsl */
    var0.i = ((orc_int64)var4.i * (orc_int64)var5.i) >> 32;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_mulhul (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: mulhul */
    var0.i = ((orc_uint64)var4.i * (orc_uint64)var5.i) >> 32;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_orl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: orl */
    var0.i = var4.i | var5.i;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_shll (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  const int var24 = ((orc_union32 *)(ex->src_ptrs[1]))->i;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: shll */
    var0.i = var4.i << var24;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_shrsl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  const int var24 = ((orc_union32 *)(ex->src_ptrs[1]))->i;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: shrsl */
    var0.i = var4.i >> var24;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_shrul (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  const int var24 = ((orc_union32 *)(ex->src_ptrs[1]))->i;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: shrul */
    var0.i = ((orc_uint32)var4.i) >> var24;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_signl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: signl */
    var0.i = ORC_CLAMP(var4.i,-1,1);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_storel (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: storel */
    var0.i = var4.i;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_subl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: subl */
    var0.i = var4.i - var5.i;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_subssl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: subssl */
    var0.i = ORC_CLAMP_SL((orc_int64)var4.i - (orc_int64)var5.i);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_subusl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: subusl */
    var0.i = ORC_CLAMP_UL((orc_int64)(orc_uint32)var4.i - (orc_int64)(orc_uint32)var5.i);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_xorl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: xorl */
    var0.i = var4.i ^ var5.i;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_convsbw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: convsbw */
    var0 = var4;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_convubw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: convubw */
    var0 = (orc_uint8)var4;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_convswl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: convswl */
    var0.i = var4;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_convuwl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: convuwl */
    var0.i = (orc_uint16)var4;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_convwb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: convwb */
    var0 = var4;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_convssswb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: convssswb */
    var0 = ORC_CLAMP_SB(var4);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_convsuswb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: convsuswb */
    var0 = ORC_CLAMP_UB(var4);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_convusswb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: convusswb */
    var0 = ORC_CLAMP_SB((orc_uint16)var4);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_convuuswb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: convuuswb */
    var0 = ORC_CLAMP_UB((orc_uint16)var4);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_convlw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: convlw */
    var0 = var4.i;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_convssslw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: convssslw */
    var0 = ORC_CLAMP_SW(var4.i);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_convsuslw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: convsuslw */
    var0 = ORC_CLAMP_UW(var4.i);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_convusslw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: convusslw */
    var0 = ORC_CLAMP_SW((orc_uint32)var4.i);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_convuuslw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: convuuslw */
    var0 = ORC_CLAMP_UW((orc_uint32)var4.i);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_mulsbw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: mulsbw */
    var0 = var4 * var5;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_mulubw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: mulubw */
    var0 = (orc_uint8)var4 * (orc_uint8)var5;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_mulswl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: mulswl */
    var0.i = var4 * var5;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_muluwl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: muluwl */
    var0.i = (orc_uint16)var4 * (orc_uint16)var5;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_accw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var12 = 0;

  ptr4 = (orc_int16 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: accw */
    var12 = var12 + var4;
  }
  ((orc_union32 *)ex->dest_ptrs[0])->i = (var12 + ((orc_union32 *)ex->dest_ptrs[0])->i) & 0xffff;

}

void
emulate_accl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var12 =  { 0 };

  ptr4 = (orc_union32 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: accl */
    var12.i = var12.i + var4.i;
  }
  ((orc_union32 *)ex->dest_ptrs[0])->i += var12.i;

}

void
emulate_accsadubl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;
  orc_union32 var12 =  { 0 };

  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: accsadubl */
    var12.i = var12.i + ORC_ABS((orc_int32)(orc_uint8)var4 - (orc_int32)(orc_uint8)var5);
  }
  ((orc_union32 *)ex->dest_ptrs[0])->i += var12.i;

}

void
emulate_swapw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: swapw */
    var0 = ORC_SWAP_W(var4);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_swapl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: swapl */
    var0.i = ORC_SWAP_L(var4.i);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_select0wb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: select0wb */
    var0 = (orc_uint16)var4 & 0xff;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_select1wb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: select1wb */
    var0 = ((orc_uint16)var4 >> 8)&0xff;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_select0lw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: select0lw */
    var0 = (orc_uint32)var4.i & 0xffff;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_select1lw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: select1lw */
    var0 = ((orc_uint32)var4.i >> 16)&0xffff;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_mergewl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_int16 var4;
  const orc_int16 * ptr4;
  orc_int16 var5;
  const orc_int16 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];
  ptr5 = (orc_int16 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: mergewl */
    var0.i = ((orc_uint16)var4) | ((orc_uint16)var5 << 16);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_mergebw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int8 var4;
  const orc_int8 * ptr4;
  orc_int8 var5;
  const orc_int8 * ptr5;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr4 = (orc_int8 *)ex->src_ptrs[0];
  ptr5 = (orc_int8 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: mergebw */
    var0 = ((orc_uint8)var4) | ((orc_uint8)var5 << 8);
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_splitlw (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int16 var0;
  orc_int16 * ptr0;
  orc_int16 var1;
  orc_int16 * ptr1;
  orc_union32 var4;
  const orc_union32 * ptr4;

  ptr0 = (orc_int16 *)ex->dest_ptrs[0];
  ptr1 = (orc_int16 *)ex->dest_ptrs[1];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: splitlw */
    var0 = (var4.i >> 16) & 0xffff;
    var1 = var4.i & 0xffff;
    *ptr0 = var0;
    ptr0++;
    *ptr1 = var1;
    ptr1++;
  }

}

void
emulate_splitwb (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_int8 var0;
  orc_int8 * ptr0;
  orc_int8 var1;
  orc_int8 * ptr1;
  orc_int16 var4;
  const orc_int16 * ptr4;

  ptr0 = (orc_int8 *)ex->dest_ptrs[0];
  ptr1 = (orc_int8 *)ex->dest_ptrs[1];
  ptr4 = (orc_int16 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: splitwb */
    var0 = (var4 >> 8) & 0xff;
    var1 = var4 & 0xff;
    *ptr0 = var0;
    ptr0++;
    *ptr1 = var1;
    ptr1++;
  }

}

void
emulate_addf (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: addf */
    var0.f = ORC_DENORMAL(ORC_DENORMAL(var4.f) + ORC_DENORMAL(var5.f));
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_subf (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: subf */
    var0.f = ORC_DENORMAL(ORC_DENORMAL(var4.f) - ORC_DENORMAL(var5.f));
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_mulf (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: mulf */
    var0.f = ORC_DENORMAL(ORC_DENORMAL(var4.f) * ORC_DENORMAL(var5.f));
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_divf (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: divf */
    var0.f = ORC_DENORMAL(ORC_DENORMAL(var4.f) / ORC_DENORMAL(var5.f));
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_sqrtf (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: sqrtf */
    var0.f = sqrt(ORC_DENORMAL(var4.f));
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_maxf (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: maxf */
    var0.f = ORC_MAXF(ORC_DENORMAL(var4.f),ORC_DENORMAL(var5.f));
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_minf (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: minf */
    var0.f = ORC_MINF(ORC_DENORMAL(var4.f),ORC_DENORMAL(var5.f));
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_cmpeqf (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: cmpeqf */
    var0.i = (ORC_DENORMAL(var4.f) == ORC_DENORMAL(var5.f)) ? (~0) : 0;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_cmpltf (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: cmpltf */
    var0.i = (ORC_DENORMAL(var4.f) < ORC_DENORMAL(var5.f)) ? (~0) : 0;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_cmplef (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;
  orc_union32 var5;
  const orc_union32 * ptr5;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];
  ptr5 = (orc_union32 *)ex->src_ptrs[1];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    var5 = *ptr5;
    ptr5++;
    /* 0: cmplef */
    var0.i = (ORC_DENORMAL(var4.f) <= ORC_DENORMAL(var5.f)) ? (~0) : 0;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_convfl (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: convfl */
    var0.i = (int)var4.f;
    *ptr0 = var0;
    ptr0++;
  }

}

void
emulate_convlf (OrcOpcodeExecutor *ex, int n)
{
  int i;
  orc_union32 var0;
  orc_union32 * ptr0;
  orc_union32 var4;
  const orc_union32 * ptr4;

  ptr0 = (orc_union32 *)ex->dest_ptrs[0];
  ptr4 = (orc_union32 *)ex->src_ptrs[0];

  for (i = 0; i < n; i++) {
    var4 = *ptr4;
    ptr4++;
    /* 0: convlf */
    var0.f = var4.i;
    *ptr0 = var0;
    ptr0++;
  }

}

