
/* autogenerated from orcfunctions.orc */

#ifndef _ORCFUNCTIONS_H_
#define _ORCFUNCTIONS_H_


#ifdef __cplusplus
extern "C" {
#endif

void orc_memcpy (void * d1, const void * s1, int n);
void orc_memset (void * d1, int p1, int n);

#ifdef __cplusplus
}
#endif

#endif

